name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
  runs-on: ubuntu-latest
  steps:
  # uses GitHub's checkout action to checkout code from the master branch
  uses: actions/checkout@v2
