name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the master branch
    - uses: actions/checkout@v2.3.4
    
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5
    
    # publishes Blazor project to the release folder
    - name: Publish .NET Core Project
      run: dotnet publish CovidTestCenters.csproj -c Release -o release --nologo
