name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [main]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the master branch
    - uses: actions/checkout@v2.3.4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x'
    

    
    - name: Install node libraries
      working-directory: CovidTestCentres/CovidTestCentres.Client
      run: npm install tailwindcss postcss autoprefixer postcss-cli      
      
    # publishes Blazor project to the release folder
    - name: Publish .NET Core Project
      run: dotnet publish CovidTestCentres/CovidTestCentres.Client/CovidTestCentres.Client.csproj -c Release -o release --nologo
